#!/bin/bash
# Clog Dir
  cl="$PWD"
  function upset() {
    printf "\n\nWarning: running this will remove any existing blog settings in clogrc.\n\nDo you with to proceed? (y/n) "
    read yn
    if [[ ${yn} = "n" ]] || [[ ${yn} = "no" ]] ; then exit 0 ; fi
    printf "Blog Title: "
    read blogtitle
    printf "Blog Description: "
    read blogdesc
    echo title:${blogtitle} > .clogrc
    echo descr:${blogdesc} >> .clogrc
  }
# Update Index Page
  function indexpage {
  # Create Index File, Listing Posts, Etc.
    title=$(grep "title" .clogrc | sed -e "s/title://")
    descr=$(grep "descr" .clogrc | sed -e "s/descr://")
  # Header
    echo $(sed "s/<!--BLOG-TITLE-->/${title}/;s/<!--BLOG-DESCRIPTION-->/${descr}/" src/head.html) > index.html
    echo "<h1>${title}</h1>" >> index.html
    echo "<p>${descr}</p>" >> index.html
  # Post Sort and Main Body
    postlist=$(ls -t posts)
    postlist=$(sed 's/drafts//g;s/published//g' <<< ${postlist})
    plarr=($postlist)
    for i in "${plarr[@]}" ; do
      filenm="posts/${i}"
      ptitle=$(grep '<h1>' ${filenm} | sed "s/^\<h1\>.*\<\/h1\>//g")
      ptitle=$(sed "s/<h1>//g;s/<\/h1>//g" <<< "${ptitle}")
      echo "<div>" >> index.html
      echo "  <a href=\"$filenm\">" >> index.html
      echo "    <h3>" >>index.html
      echo "      ${ptitle}" >> index.html
      echo "    </h3>">>index.html
      echo "  </a>" >> index.html
      echo "</div>" >> index.html
    done
  # Footer
    cat "src/footer.html" >> index.html
  }
# List Files In A Folder
  function listfiles {
    echo ""
    count=1
    for file in ${loc} ; do
      echo "   ${count}: ${file##*/}"
      count=$((count+1))
    done
    echo ""
  }  
# Create Draft Post
  function add() {
    printf "What would you like to call the post? "
    read -r posttitle
    posttitle=$(sed "s/ /-/g" <<< "${posttitle}")
    vim "posts/drafts/${posttitle}.md"
  }
# Publish Post
  function pub {
    # Get Post to Post
    while true ; do
      loc="posts/drafts/*"
      listfiles
      printf "Which draft would you like to post? "
      read -r posttopost
      reg='^[0-9]+$'
      if [[ ${posttopost} =~ ${reg} ]] ; then 
        listfiles > ./tmp
        posttopost="1"
        posttopost=$(grep "${posttopost}:" "./tmp" | \
                     cut -d':' -f2 | cut -d' ' -f2)
        rm ./tmp
      fi
      if [[ ! ${posttopost} == *".md"* ]] ; then 
        posttopost=${posttopost}.md 
      fi
      if [ ! -f "posts/drafts/${posttopost}" ] ; then
        echo "" 
        echo "There has been an error. 
              We can't find the post you're looking for." 
        echo "Please try again."
      else
        break
      fi
    done 
    filename="posts/drafts/$(echo "${posttopost}" | cut -d "." -f 1).html"
    printf "What is the title of the post? "
    read title
    printf "Short post description: "
    read descr
    ul="false"
    # HEAD
    echo $(sed "s/<!--BLOG-TITLE-->/${title}/;s/<!--BLOG-DESCRIPTION-->/${descr}/" src/head.html) > "${filename}"
    # BODY
    echo "<!--POSTDATE:$(date +%Y/%m/%d-%H-%M)-->" >> "${filename}"
    while read -r line ; do
      # Skip if empty line
      if [[ -z ${line} ]] ; then continue ; fi
      # Heading 6
      if [[ ${line} == *"###### "* ]] ; then
        if [[ ${ul} = "true" ]] ; then echo "</ul>" >> "${filename}" ; ul="false" ; fi
        h6="###### "
        printf '%s\n' "<h6>${line//$h6/}</h6>" >> "${filename}"
      # Heading 5
      elif [[ ${line} == *"##### "* ]] ; then
        if [[ ${ul} = "true" ]] ; then echo "</ul>" >> "${filename}" ; ul="false" ; fi
        h5="##### "
        printf '%s\n' "<h5>${line//$h5/}</h5>" >> "${filename}"
      # Heading 4
      elif [[ ${line} == *"#### "* ]] ; then
        if [[ ${ul} = "true" ]] ; then echo "</ul>" >> "${filename}" ; ul="false" ; fi
        h4="#### "
        printf '%s\n' "<h4>${line//$h4/}</h4>" >> "${filename}"
      # Heading 3
      elif [[ ${line} == *"### "* ]] ; then
        if [[ ${ul} = "true" ]] ; then echo "</ul>" >> "${filename}" ; ul="false" ; fi
        h3="### "
        printf '%s\n' "<h3>${line//$h3/}</h3>" >> "${filename}"
      # Heading 2
      elif [[ ${line} == *"## "* ]] ; then
        if [[ ${ul} = "true" ]] ; then echo "</ul>" >> "${filename}" ; ul="false" ; fi
        h2="## "
        printf '%s\n' "<h2>${line//$h2/}</h2>" >> "${filename}"
      # Heading 1
      elif [[ ${line} == *"# "* ]] ; then
        if [[ ${ul} = "true" ]] ; then echo "</ul>" >> "${filename}" ; ul="false" ; fi
        h1="# "
        printf '%s\n' "<h1>${line//$h1/}</h1>" >> "${filename}"
      # UL
      elif [[ ${line} == *"- "* ]] ; then
        bulletpoint="- "
        if [[ ${ul} = "false" ]] ; then echo "<ul>" >> "${filename}" ; fi
        ul="true"
        printf '%s\n' "<li><p>${line//$bulletpoint/}</p></li>" >> "${filename}"
      # Paragraph Standard
      else
        if [[ ${ul} = "true" ]] ; then echo "</ul>" >> "${filename}" ; ul="false" ; fi
        echo "<p>${line}</p>" >> "${filename}"
      fi
    done < "posts/drafts/${posttopost}"
    # FOOT
    cat "src/footer.html" >> "${filename}"
  # Moving .html To Correct Place
    if [ ! -d "posts/published" ] ; then mkdir "posts/published" ; fi
    mv "posts/drafts/${posttopost}" "posts/published/${posttopost}" 
    mv "${filename}" posts
  }
# Remove Post
  function rem {
    while true ; do
      listlocation="posts/*.html"
      listfiles
      if [[ $listfiles = "*.html" ]] ; then echo "No Posts Found To Remove"; exit 0; fi
      printf "Which post would you like to remove? "
      read -r posttoremove
      echo "${posttoremove}"
      reg='^[0-9]+$' 
      if [[ ${posttoremove} =~ ${reg} ]] ; then 
        listfiles > ./tmp
        posttoremove="1"
        posttoremove=$(grep "${posttoremove}:" "./tmp" | \
                    cut -d':' -f2 | cut -d' ' -f2)
        rm ./tmp
      fi
      if [ ! -f "posts/${posttoremove}" ] ; then
        echo "" 
        echo "There has been an error. We can't find the post you're looking for." 
        echo "Please try again."
      else
        break
      fi
    done 
    rm "posts/${posttoremove}"
  }
# Usage Instructions
  function usage() {
    echo "This instruction needs a valid argument:"
    echo " - add / new           create a draft post"
    echo " - post / publish      publish a draft post"
    echo " - remove              remove a published post"
  }
# Deal With Arguments 
  case "${1}" in 
    add|new) 
      add
      ;;
    post|publish) 
      pub
      ;;
    rm|remove) 
      rem
      ;;
    setup)
      upset
      ;;
    *) usage
  esac 
# Update the index page
  indexpage
