#!/bin/bash

# Warning
  printf "\n\nWarning: running this will remove any existing blog settings in clogrc.\n\nDo you with to proceed? (y/n) "
  read yn
  if [[ ${yn} = "n" ]] || [[ ${yn} = "no" ]] ; then exit 0 ; fi

# Blog Title
  printf "Blog Title: "
  read blogtitle

# Blog Description
  printf "Blog Description: "
  read blogdesc

# Print To File
  echo title:${blogtitle} > .clogrc
  echo descr:${blogdesc} >> .clogrc

# Re-Format Home
  bin/home
